package athletics.model;

public enum Type {
FEMALE_CLOHTES,
MALE_CLOTHES,
KID_MALE_CLOTHES,
KID_FEMALE_CLOTHES,
FEMALE_SHOES,
MALE_SHOES,
KID_MALE_SHOES,
KID_FEMALE_SHOES
//TO BE CONTINUED
}
